config/routes.rb
Rails.application.routes.draw do
  resources :vendas
  resources :produtos
  resources :clientes
  resources :usuario_perfils
  resources :perfils
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/usuario_perfil.rb
class UsuarioPerfil < ApplicationRecord
end

app/controllers/usuario_perfils_controller.rb
class UsuarioPerfilsController < ApplicationController
  before_action :set_usuario_perfil, only: [:show, :edit, :update, :destroy]

  # GET /usuario_perfils
  # GET /usuario_perfils.json
  def index
    @usuario_perfils = UsuarioPerfil.all
  end

  # GET /usuario_perfils/1
  # GET /usuario_perfils/1.json
  def show
  end

  # GET /usuario_perfils/new
  def new
    @usuario_perfil = UsuarioPerfil.new
  end

  # GET /usuario_perfils/1/edit
  def edit
  end

  # POST /usuario_perfils
  # POST /usuario_perfils.json
  def create
    @usuario_perfil = UsuarioPerfil.new(usuario_perfil_params)

    respond_to do |format|
      if @usuario_perfil.save
        format.html { redirect_to @usuario_perfil, notice: 'Usuario perfil was successfully created.' }
        format.json { render :show, status: :created, location: @usuario_perfil }
      else
        format.html { render :new }
        format.json { render json: @usuario_perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuario_perfils/1
  # PATCH/PUT /usuario_perfils/1.json
  def update
    respond_to do |format|
      if @usuario_perfil.update(usuario_perfil_params)
        format.html { redirect_to @usuario_perfil, notice: 'Usuario perfil was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario_perfil }
      else
        format.html { render :edit }
        format.json { render json: @usuario_perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuario_perfils/1
  # DELETE /usuario_perfils/1.json
  def destroy
    @usuario_perfil.destroy
    respond_to do |format|
      format.html { redirect_to usuario_perfils_url, notice: 'Usuario perfil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario_perfil
      @usuario_perfil = UsuarioPerfil.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_perfil_params
      params.require(:usuario_perfil).permit(:nome)
    end
end

app/helpers/usuario_perfils_helper.rb
module UsuarioPerfilsHelper
end

app/views/usuario_perfils/_form.html.erb
<%= form_with(model: usuario_perfil, local: true) do |form| %>
  <% if usuario_perfil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario_perfil.errors.count, "error") %> prohibited this usuario_perfil from being saved:</h2>

      <ul>
      <% usuario_perfil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuario_perfils/edit.html.erb
<h1>Editing Usuario Perfil</h1>

<%= render 'form', usuario_perfil: @usuario_perfil %>

<%= link_to 'Show', @usuario_perfil %> |
<%= link_to 'Back', usuario_perfils_path %>

app/views/usuario_perfils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuario Perfils</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuario_perfils.each do |usuario_perfil| %>
      <tr>
        <td><%= usuario_perfil.nome %></td>
        <td><%= link_to 'Show', usuario_perfil %></td>
        <td><%= link_to 'Edit', edit_usuario_perfil_path(usuario_perfil) %></td>
        <td><%= link_to 'Destroy', usuario_perfil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario Perfil', new_usuario_perfil_path %>

app/views/usuario_perfils/new.html.erb
<h1>New Usuario Perfil</h1>

<%= render 'form', usuario_perfil: @usuario_perfil %>

<%= link_to 'Back', usuario_perfils_path %>

app/views/usuario_perfils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario_perfil.nome %>
</p>

<%= link_to 'Edit', edit_usuario_perfil_path(@usuario_perfil) %> |
<%= link_to 'Back', usuario_perfils_path %>