config/routes.rb
Rails.application.routes.draw do
  resources :vendas
  resources :produtos
  resources :clientes
  resources :usuario_perfils
  resources :perfils
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/perfil.rb
class Perfil < ApplicationRecord
end

app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController
  before_action :set_perfil, only: [:show, :edit, :update, :destroy]

  # GET /perfils
  # GET /perfils.json
  def index
    @perfils = Perfil.all
  end

  # GET /perfils/1
  # GET /perfils/1.json
  def show
  end

  # GET /perfils/new
  def new
    @perfil = Perfil.new
  end

  # GET /perfils/1/edit
  def edit
  end

  # POST /perfils
  # POST /perfils.json
  def create
    @perfil = Perfil.new(perfil_params)

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to @perfil, notice: 'Perfil was successfully created.' }
        format.json { render :show, status: :created, location: @perfil }
      else
        format.html { render :new }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfils/1
  # PATCH/PUT /perfils/1.json
  def update
    respond_to do |format|
      if @perfil.update(perfil_params)
        format.html { redirect_to @perfil, notice: 'Perfil was successfully updated.' }
        format.json { render :show, status: :ok, location: @perfil }
      else
        format.html { render :edit }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfils/1
  # DELETE /perfils/1.json
  def destroy
    @perfil.destroy
    respond_to do |format|
      format.html { redirect_to perfils_url, notice: 'Perfil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil
      @perfil = Perfil.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def perfil_params
      params.require(:perfil).permit(:nome)
    end
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/views/perfils/_form.html.erb
<%= form_with(model: perfil, local: true) do |form| %>
  <% if perfil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perfil.errors.count, "error") %> prohibited this perfil from being saved:</h2>

      <ul>
      <% perfil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/perfils/edit.html.erb
<h1>Editando Perfil</h1>

<%= render 'form', perfil: @perfil %>

<%= link_to 'Mostrar', @perfil %> |
<%= link_to 'Voltar', perfils_path %>

app/views/perfils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Perfils</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perfils.each do |perfil| %>
      <tr>
        <td><%= perfil.nome %></td>
        <td><%= link_to 'Mostrar', perfil %></td>
        <td><%= link_to 'Editar', edit_perfil_path(perfil) %></td>
        <td><%= link_to 'Apagar', perfil, method: :delete, data: { confirm: 'Tem certeza disso?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar perfil', new_perfil_path %>

app/views/perfils/new.html.erb
<h1>Novo perfil</h1>

<%= render 'form', perfil: @perfil %>

<%= link_to 'Voltar', perfils_path %>

app/views/perfils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @perfil.nome %>
</p>

<%= link_to 'Editar', edit_perfil_path(@perfil) %> |
<%= link_to 'Voltar', perfils_path %>